/*
 * Copyright 2025-present the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
package io.github.simplejdbcmapper.core;

import java.lang.reflect.Constructor;
import java.sql.ResultSet;
import java.sql.SQLException;

import org.springframework.core.convert.ConversionService;
import org.springframework.jdbc.core.RowMapper;

import io.github.simplejdbcmapper.exception.MapperException;

/**
 * A row mapper for mapped objects.
 * 
 * Use the method
 * {@link io.github.simplejdbcmapper.core.SimpleJdbcMapper#newEntityRowMapper}
 * to get an instance of EntityRowMapper.
 * 
 * <p>
 * EntityRowMapper <b>always</b> has to be used with sql columns generated by
 * either
 * 
 * <pre>
 * getEntitySqlColumns({@code Class<?>} entityType) or
 * getEntitySqlColumns({@code Class<?>} entityType, String tableAlias).
 * </pre>
 * 
 * <p>
 * It expects the sql columns to be exactly in a specific order because it uses
 * position indexes to retrieve the data from the query ResultSet. It will
 * handle the cases where the column to property mappings do not follow the
 * underscore to camel case naming convention.
 * 
 * <p>
 * This is the recommended row mapper to use when writing custom queries for
 * mapped objects. It has optimizations which allows it to process data from the
 * query ResultSet in a performant way.
 * 
 * <p>
 * Query:
 * 
 * <pre>
 * String sql = "SELECT " + sjm.getEntitySqlColumns(Product.class) + "FROM product WHERE name = ?";
 * </pre>
 * 
 * Example using JdbcTemplate:
 * 
 * <pre>
 * {@code List<Product>} products = sjm.getJdbcTemplate().query(sql, sjm.newEntityRowMapper(Product.class), "someProductName");
 * </pre>
 * <p>
 * Example using JdbcClient. Note that the EntityRowMapper has to be passed in
 * as an argument, otherwise JdbcClient will use its internal row mapper
 * SimplePropertyRowMapper which will not work with the sql.
 * 
 * <pre>
 * {@code List<Product>} products = sjm.getJdbcClient().sql(sql)
 *                                                     .param("someProductName")
 *                                                     .query(sjm.newEntityRowMapper(Product.class))
 *                                                     .list();
 * </pre>
 * 
 * @param <T> the entityType
 * 
 * @author Antony Joseph
 */
public final class EntityRowMapper<T> implements RowMapper<T> {
	private final ConversionService conversionService;
	private final PropertyMapping[] propertyMappings;
	private final Constructor<T> mappedObjConstructor;
	private final int startIndex;
	private final int endIndex;

	@SuppressWarnings("unchecked")
	EntityRowMapper(TableMapping tableMapping, ConversionService conversionService, int offset) {
		this.conversionService = conversionService;
		this.propertyMappings = tableMapping.getPropertyMappings();
		this.mappedObjConstructor = tableMapping.getMappedObjConstructor();
		this.startIndex = offset;
		this.endIndex = propertyMappings.length + offset - 1;
	}

	@Override
	public T mapRow(ResultSet rs, int rowNumber) throws SQLException {
		T obj = null;
		try {
			obj = mappedObjConstructor.newInstance();
			boolean[] typedValueExtracted = { true };
			// since the columns sql was generated using the property mappings the resultset
			// columns will be in same order.
			for (int index = startIndex; index <= endIndex; index++) {
				PropertyMapping propMapping = propertyMappings[index - startIndex];
				Object value = InternalUtils.getResultSetValue(rs, index, propMapping.getResultSetType(),
						propMapping.getPropertyType(), typedValueExtracted);
				if (typedValueExtracted[0] || value == null) {
					propMapping.getWriteMethod().invoke(obj, value);
				} else {
					propMapping.getWriteMethod().invoke(obj,
							conversionService.convert(value, propMapping.getPropertyType()));
				}
			}
		} catch (Exception e) {
			throw new MapperException(e.getMessage(), e);
		}
		return obj;
	}

}