package io.github.simplejdbcmapper.core;

import java.lang.reflect.Field;
import java.sql.DatabaseMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

import javax.sql.DataSource;

import org.springframework.core.annotation.AnnotationUtils;
import org.springframework.jdbc.support.DatabaseMetaDataCallback;
import org.springframework.jdbc.support.JdbcUtils;
import org.springframework.jdbc.support.MetaDataAccessException;
import org.springframework.util.Assert;
import org.springframework.util.StringUtils;

import io.github.simplejdbcmapper.annotation.Id;
import io.github.simplejdbcmapper.annotation.IdType;
import io.github.simplejdbcmapper.annotation.Table;
import io.github.simplejdbcmapper.exception.AnnotationException;
import io.github.simplejdbcmapper.exception.MapperException;

class TableMappingProvider {
	private final DataSource dataSource;

	private final String schemaName;

	private final String catalogName;

	// Map key - class name
	// value - the table mapping
	private final SimpleCache<String, TableMapping> tableMappingCache = new SimpleCache<>();

	private final AnnotationProcessor ap;

	private String commonDatabaseName;

	public TableMappingProvider(DataSource dataSource, String schemaName, String catalogName) {
		this.dataSource = dataSource;
		this.schemaName = schemaName;
		this.catalogName = catalogName;
		this.ap = new AnnotationProcessor();
	}

	TableMapping getTableMapping(Class<?> entityType) {
		Assert.notNull(entityType, "entityType must not be null");
		TableMapping tableMapping = tableMappingCache.get(entityType.getName());
		if (tableMapping == null) {
			Table tableAnnotation = ap.getTableAnnotation(entityType);
			String tableName = tableAnnotation.name();
			String catalog = getCatalogForTable(tableAnnotation);
			String schema = getSchemaForTable(tableAnnotation);
			validateMetaDataConfig(catalog, schema);
			List<Field> fields = getAllFields(entityType);
			IdPropertyInfo idPropertyInfo = getIdPropertyInfo(entityType, fields);
			List<PropertyMapping> propertyMappings = getPropertyMappings(entityType, tableName, catalog, schema,
					fields);
			tableMapping = new TableMapping(entityType, tableName, schema, catalog, idPropertyInfo, propertyMappings);
			tableMappingCache.put(entityType.getName(), tableMapping);
		}
		return tableMapping;
	}

	SimpleCache<String, TableMapping> getTableMappingCache() {
		return tableMappingCache;
	}

	private List<PropertyMapping> getPropertyMappings(Class<?> entityType, String tableName, String catalog,
			String schema, List<Field> fields) {
		// key:propertyName, value:PropertyMapping. LinkedHashMap to maintain order of
		// properties
		Map<String, PropertyMapping> propNameToPropertyMapping = new LinkedHashMap<>();
		for (Field field : fields) {
			// process column annotation always first
			ap.processColumnAnnotation(field, tableName, propNameToPropertyMapping);
			ap.processIdAnnotation(field, tableName, propNameToPropertyMapping);
			ap.processVersionAnnotation(field, tableName, propNameToPropertyMapping);
			ap.processCreatedOnAnnotation(field, tableName, propNameToPropertyMapping);
			ap.processUpdatedOnAnnotation(field, tableName, propNameToPropertyMapping);
			ap.processCreatedByAnnotation(field, tableName, propNameToPropertyMapping);
			ap.processUpdatedByAnnotation(field, tableName, propNameToPropertyMapping);
		}
		List<PropertyMapping> propertyMappings = new ArrayList<>(propNameToPropertyMapping.values());
		ap.validateAnnotations(propertyMappings, entityType);
		return propertyMappings;
	}

	private List<Field> getAllFields(Class<?> entityType) {
		List<Field> fields = new ArrayList<>();
		Class<?> clazz = entityType;
		while (clazz != null && clazz != Object.class) {
			Collections.addAll(fields, clazz.getDeclaredFields());
			clazz = clazz.getSuperclass();
		}
		// there could be duplicate fields due to super classes. Get unique fields list
		// by name
		Set<String> set = new HashSet<>();
		return fields.stream().filter(p -> set.add(p.getName())).toList();
	}

	private IdPropertyInfo getIdPropertyInfo(Class<?> entityType, List<Field> fields) {
		Id idAnnotation = null;
		String idPropertyName = null;
		boolean isIdAutoGenerated = false;
		for (Field field : fields) {
			idAnnotation = AnnotationUtils.findAnnotation(field, Id.class);
			if (idAnnotation != null) {
				if (field.getType().isPrimitive()) {
					throw new AnnotationException(entityType.getSimpleName() + "." + idPropertyName
							+ " is an id and cannot be a primitive type.");
				}
				idPropertyName = field.getName();
				if (idAnnotation.type() == IdType.AUTO_GENERATED) {
					isIdAutoGenerated = true;
				}
				break;
			}
		}
		if (idAnnotation == null) {
			throw new AnnotationException(
					"@Id annotation not found in class " + entityType.getSimpleName() + " . It is required");
		}
		return new IdPropertyInfo(idPropertyName, isIdAutoGenerated);
	}

	private String getCatalogForTable(Table tableAnnotation) {
		return StringUtils.hasText(tableAnnotation.catalog()) ? tableAnnotation.catalog() : catalogName;
	}

	private String getSchemaForTable(Table tableAnnotation) {
		return StringUtils.hasText(tableAnnotation.schema()) ? tableAnnotation.schema() : schemaName;
	}

	private void validateMetaDataConfig(String catalog, String schema) {
		String databaseName = getCommonDatabaseName();
		if ("mysql".equalsIgnoreCase(databaseName) && schema != null) {
			throw new MapperException(databaseName
					+ ": When creating SimpleJdbcMapper() if you are using 'schema' (argument 2) use 'catalog' (argument 3) instead."
					+ " If you are using the @Table annotation use the 'catalog' attribue instead of 'schema' attribute");
		}
		if ("oracle".equalsIgnoreCase(databaseName) && catalog != null) {
			throw new MapperException(databaseName
					+ ": When creating SimpleJdbcMapper() if you are using the 'catalog' (argument 3) use 'schema' (argument 2) instead."
					+ " If you are using the @Table annotation use the 'schema' attribue instead of 'catalog' attribute");
		}
	}

	private String getCommonDatabaseName() {
		// Even if there is thread contention and commonDatabaseName gets set more than
		// once there are no side effects.
		if (commonDatabaseName == null) {
			try {
				String dbProductName = JdbcUtils.extractDatabaseMetaData(dataSource,
						new DatabaseMetaDataCallback<String>() {
							public String processMetaData(DatabaseMetaData dbMetaData)
									throws SQLException, MetaDataAccessException {
								return dbMetaData.getDatabaseProductName() == null ? ""
										: dbMetaData.getDatabaseProductName();
							}
						});
				commonDatabaseName = JdbcUtils.commonDatabaseName(dbProductName);
			} catch (Exception e) {
				throw new MapperException(e);
			}
		}
		return commonDatabaseName;
	}
}
