name: CI SimpleJdbcMapper

#on:
#  workflow_dispatch:
on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]
    
jobs:
  tests-against-postgres:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_DB: sjm_postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: pass1234
        ports:
          # Maps service port to port on the runner host
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'corretto'
        cache: maven
        
    # dont want the step of running tests be polluted by dependency downloads
    - name: Download dependencies and plugins
      run: mvn dependency:go-offline dependency:resolve dependency:resolve-plugins
      
    - name: Run tests against postgres
      run: mvn clean package -Dspring.profiles.active=postgres -Djacoco.destFile=${{ github.workspace }}/target/postgres-jacoco.exec
      
    - name: List working directory
      run: ls -R

    - name: upload jacoco exec
      uses: actions/upload-artifact@v6
      with:
        name: postgres_jacoco_exec
        path: ${{ github.workspace }}/target/postgres-jacoco.exec
    

  tests-against-mysql:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: sjm_mysql
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

        # Maps service port to port on the runner host
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'corretto'
        cache: maven

    # dont want the step of running tests be polluted by dependency downloads
    - name: Download dependencies and plugins
      run: mvn dependency:go-offline dependency:resolve dependency:resolve-plugins
      
    - name: Run tests against mysql
      run: mvn clean package -Dspring.profiles.active=mysql -Djacoco.destFile=${{ github.workspace }}/target/mysql-jacoco.exec
      
    - name: upload jacoco exec
      uses: actions/upload-artifact@v6
      with:
        name: mysql_jacoco_exec
        path: ${{ github.workspace }}/target/mysql-jacoco.exec
        
  tests-against-oracle:
    runs-on: ubuntu-latest
    
    services:
      # Oracle service (label used to access the service container)
      oracle:
        image: gvenzl/oracle-free:latest
        
        # Provide passwords and other environment variables to container
        env:
          ORACLE_PASSWORD: pass1234
          APP_USER: SCHEMA1
          APP_USER_PASSWORD: app
 
        # Maps service port to port on the runner host
        ports:
          - 1521:1521

        # Provide container name and healthcheck script options for startup
        options: >-
          --name oracle-db 
          --health-cmd healthcheck.sh
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:       
    - name: Checkout code
      uses: actions/checkout@v6
       
    - name: initialize oracle setup
      run: |
        docker cp src/test/resources/db/oracle_setup.sql oracle-db:/tmp/oracle_setup.sql
        docker exec oracle-db sqlplus system/pass1234@FREEPDB1 @/tmp/oracle_setup.sql  
       
    - name: Set up JDK 21
      uses: actions/setup-java@v5        
      with:
        java-version: '21'
        distribution: 'corretto'
        cache: maven
        
    # dont want the step of running tests be polluted by dependency downloads                
    - name: Download dependencies and plugins
      run: mvn dependency:go-offline dependency:resolve dependency:resolve-plugins
      
    - name: Run tests against oracle
      run: mvn clean package -Dspring.profiles.active=oracle -Djacoco.destFile=${{ github.workspace }}/target/oracle-jacoco.exec
      
    - name: upload jacoco exec
      uses: actions/upload-artifact@v6
      with:
        name: oracle_jacoco_exec
        path: ${{ github.workspace }}/target/oracle-jacoco.exec
      
  tests-against-sqlserver:
    runs-on: ubuntu-latest
    
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: 'Y'
          MSSQL_SA_PASSWORD: Mssql123
          
        # Maps service port to port on the runner host 
        ports:
          - 1433:1433
          
        # Health check ensures the service is ready before steps run
        options: >-
          --health-cmd "/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P 'Mssql123' -Q 'SELECT 1'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'corretto'
        cache: maven
      
    - name: Initialize SQL Server setup
      uses: azure/sql-action@v2.3
      with:
        connection-string: Server=tcp:localhost,1433;Initial Catalog=master;User ID=sa;Password=Mssql123;Encrypt=True;TrustServerCertificate=True;Connection Timeout=30;
        path: ./src/test/resources/db/sqlserver_setup.sql
        
    # dont want the step of running tests be polluted by dependency downloads
    - name: Download dependencies and plugins
      run: mvn dependency:go-offline dependency:resolve dependency:resolve-plugins
                 
    - name: Run tests against SQLServer
      run: mvn clean package -Dspring.profiles.active=sqlserver -Djacoco.destFile=${{ github.workspace }}/target/sqlserver-jacoco.exec
 
    - name: upload jacoco exec
      uses: actions/upload-artifact@v6
      with:
        name: sqlserver_jacoco_exec
        path: ${{ github.workspace }}/target/sqlserver-jacoco.exec
                   
  coverage-and-javadoc:
    needs: [tests-against-postgres, tests-against-mysql, tests-against-oracle, tests-against-sqlserver]
    
    runs-on: ubuntu-latest
   
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'corretto'
        cache: maven
       
    - name: compile
      run: mvn clean compile
      
    - name: generate javadoc
      run: mvn javadoc:javadoc
     
    - name: download all the jacoco artifacts 
      uses: actions/download-artifact@v8
      with:
        # all the *.exec files will be in workspace directory
        merge-multiple: true
    
    - name: List working directory
      run: ls -R
      
    - name: merge the jacoco exec files for all the runs
      # the default merged file will be target/jacoco.exec. See pom.xml for merge filesets info
      run: mvn jacoco:merge
      
    - name: generate the jacoco report
      run: mvn jacoco:report
            
    # This will create badge in .github/badges
    - name: Generate jacoco coverage badge
      id: jacoco
      uses: cicirello/jacoco-badge-generator@v2
      with:
        badges-directory: ./target/site/jacoco
        # Example: Green for >= 90%, Yellow for >= 75%, Red for < 75%
        colors: 'green yellow red'
        intervals: 90 75

    - name: Log the coverage percentage
      run: echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
 
    - name: list the files
      run: ls -lR
      
    - name: remove now not needed *exec files so they dont get committed
      run: rm *-jacoco.exec
            
    - name: Add javadoc and jococo reports to website branch
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        # Configure Git user (required for committing)
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
         
        git fetch origin website
        git checkout website
        
        # copy jacoco reports including svg
        cp -rf ./target/site/jacoco/. ./jacoco
        
        #copy javadocs
        cp -rf ./target/reports/apidocs/. ./javadoc
        
        # Commit and push
        # jacoco.svg is the coverage image and size stays the same. So forcefully add it.
        git add -f ./jacoco/jacoco.svg
        git add .
        git commit -m "javdoc and coverage reports from github action"
        git push origin website   
      
    
 