name: CI for SimpleJdbcMapper

on:
  push:
    branches: [ "dev" ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ "dev" ]
    paths-ignore:
      - 'README.md'

jobs:
  tests-against-sqlserver:
    runs-on: ubuntu-latest
    
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: 'Y'
          MSSQL_SA_PASSWORD: Mssql123
        ports:
          - 1433:1433
        # Health check ensures the service is ready before steps run
        options: >-
          --health-cmd "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'Mssql123' -Q 'SELECT 1'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
     
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up JDK 21
        uses: actions/setup-java@v5 # Action to set up the Java environment 
        with:
          java-version: '21' # Specify the Java version required for the Spring project
          distribution: 'corretto' # Choose a JDK distribution (e.g., temurin, corretto, zulu)
          cache: maven # Enables caching of Maven dependencies to speed up subsequent runs

      - name: init sqlserver user
        uses: azure/sql-action@v2.3
        with:
            connection-string: Server=tcp:localhost,1433;Initial Catalog=master;User ID=sa;Password=Mssql123;Encrypt=True;TrustServerCertificate=True;Connection Timeout=30;
            path: ../../../src/test/resources/db/sqlserver_setup.sql
             # required, connection string incl the database and user authentication information
             #Server=tcp:<your-server-name>.database.windows.net,1433;Initial Catalog=<your-database-name>;User ID=<your-username>;Password=<your-password>;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;        


           
    #  - name: Run tests against SQLServer
    #    run: mvn clean package -Dspring.profiles.active=sqlserver
     
      

  