name: CI for SimpleJdbcMapper

on:
  push:
    branches: [ "dev" ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ "dev" ]
    paths-ignore:
      - 'README.md'

jobs:
  tests-with-mysql:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: mysql_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s

    steps:
     - name: Set up JDK 21
       uses: actions/setup-java@v5 # Action to set up the Java environment 
       with:
         java-version: '21' # Specify the Java version required for the Spring project
         distribution: 'corretto' # Choose a JDK distribution (e.g., temurin, corretto, zulu)
         cache: maven # Enables caching of Maven dependencies to speed up subsequent runs

     - name: Run application tests
       run: mvn clean package -Dspring.profiles.active=mysql
